### ISSUE TITLE
Possibly incorrect parsing of commented tags

### ISSUE THREAD

**Issue by pr4bh4sh** [enkessler/cuke_modeler#5] opened 2020-08-06 14:38 UTC
I'm writing a custom rule which will catch the commented tags using https://github.com/enkessler/cuke_linter.

Sample scenario
```gherkin
Feature: Sample feature

  @tag #@commented_tag
  Scenario: Sample scenario
    Given I do something
    And   It's done

```

parsed model snippet
```
@tags=
       [#<CukeModeler::Tag:0x00007fcb0ecb9518
         @name="@tag #",
         @parent_model=#<CukeModeler::Scenario:0x00007fcb0ecba9e0 ...>,
         @parsing_data={:type=>:Tag, :location=>{:line=>3, :column=>3}, :name=>"@tag #"},
         @source_line=3>,
        #<CukeModeler::Tag:0x00007fcb0ecb9360
         @name="@commented_tag",
         @parent_model=#<CukeModeler::Scenario:0x00007fcb0ecba9e0 ...>,
         @parsing_data={:type=>:Tag, :location=>{:line=>3, :column=>9}, :name=>"@commented_tag"},
         @source_line=3>]>]>,
```
it parsed it as "@ tag #" and "@commented_tag", I want to ban #commented_tag.

While I can work around the currently parsed model, just wanted to know if it's worth making changes in cuke_modeler so it shows the tag as "#@commented_tag"?

**Comment by enkessler** [comment] 2020-08-08 21:46
Unfortunately, this is not a problem that is best solved by `cuke_modeler`. `cuke_modeler` just wraps the underlying Gherkin gem and provides a more convenient interface. How a feature file gets broken down into parts is entirely up to Gherkin's [grammar](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp). Personally, I'm surprised that tags can even have white space included in their names, although that may just be a quirk of the syntax rules rather than an intended design. Comments are definitely not intended to appear on the same line as other text, though.

All that being said, I think that your best best would be to use different linting rules that can work with the existing grammatical rules of Gherkin but still capture the problematic tags that you are trying to avoid. A `TagEndingInComment` or something similar that would detect any `Tag` model whose value ended with "#" might do the trick.

**Comment by enkessler** [comment] 2020-08-08 21:53
Actually, which version of `cuke_modeler`, `gherkin`, and/or `cucumber-gherkin` are you using @pr4bh4sh ? I just tried to model your example feature and there was only 1 tag modeled for the scenario. That was the first tag and it's value was only `"@tag"`.

**Comment by pr4bh4sh** [comment] 2020-08-10 15:10
I've added 'cuke_linter' as below in Gemfile
`gem 'cuke_linter'`

and the gem versions are
cuke_modeler: 1.5.1
gherkin: 4.1.3

It seems like the weird parsing is because of the cucumber version used in my project. The project I'm working on uses cucumber 2.99.0.

Looks like I'll have to work with it. Updating the cucumber gem version is not really a feasible option. We have a custom gem which depends on `cucumber (~> 2)` and will break as the new version of cucumber is not backwards compatible.

Thanks

**Comment by enkessler** [comment] 2020-08-11 07:57
When I use the same version of `gherkin` that you are, yes, I do see the same tag breakdown that you are encountering.

Given that the problem presents differently depending on the version of Gherkin being used and the fact that you are limited to specific versions, my recommendation is still to create custom linters that will detect the kind of tags that you are trying to avoid. Perhaps a linter that detects tags that include "#" in their name and/or a linter that detects comments that start with a "@".

In any case, the problem is out of scope for `cuke_modeler` and so I'll close this issue.

**Closed by enkessler** 2020-08-11 07:57 UTC

**Comment by enkessler** [comment] 2020-12-26 03:24
And apparently this kind of tag issue was found a while back...
https://github.com/cucumber/cucumber/issues/239

Fun times.
